### ISSUE TITLE
New arithmetic operation 'add' is required in the handlebar helpers set

### ISSUE THREAD

**Issue by joseeesquivel** [razee-io/MustacheTemplate#244]
**Is your feature request related to a problem? Please describe.**
There is not arithmetic operation 'add' available in Razee-io/MustacheTemplate, and I need to be able to add two numbers.

**Describe the solution you'd like**
Add a new function ('add'), in the file /src/handlebar-helpers.js that takes two numbers as input and return the sum of the two as output.

**Describe alternatives you've considered**
I haven't found an alternative in the current razee version that I'm using. I need to be able to add two numbers in a mustache template.

**Additional context**
I'm converting a jinja2 template into a mustache template and the jinja2 template has a snippet like this:
```
 spec:
        minAvailable: {{ my_prop // 2 + 1 }}
```
that I can't replicate in the mustache template without the 'add' operation

**Comment by alewitt2** [comment]
PR is merged
