### ISSUE TITLE
Razee ignores loading env/configmap on error when optional is set to true

### ISSUE THREAD

**Issue by simonkotwicz** [razee-io/MustacheTemplate#407]
It seems like if Razee fails to load a configmap for an env that is marked as optional it will just ignore the error rather than aborting the "deployment". Optional I think means only use the configmap if it’s there, ignoring it if Razee encounters an error trying to fetch the configmap is not the right behavior in my opinion.

**Comment by simonkotwicz** [comment]
@alewitt2 does your team have time to look at this?

**Comment by carrolp** [comment]
Additional background details: https://github.ibm.com/genctl/api-workspace/wiki/mtp-attributes-usage-of-%22optional%22-can-cause-production-failures

The short version is just as described here -- if an actual communication error occurs when MTP controller calls Kube apiserver (actual error, not just 'does not exist'), it should fail and halt the same way whether the 'optional' values is true or false.

**Comment by carrolp** [comment]
See also https://github.com/razee-io/razeedeploy-core/issues/300

**Comment by kdai7** [comment]
should be fixed now https://github.com/razee-io/razeedeploy-core/pull/341
