### ISSUE TITLE
Duplicate requests are generated when there is watch error and watch close within the same second

### ISSUE THREAD

**Issue by rgowrishankar** [razee-io/MustacheTemplate#461]
**Describe the bug**
We are seeing the requests to kubeapiserver double when a certain condition gets hit.
One example is:
At timestamp
[1674109129123]  GET /apis/deploy.razee.io/v1alpha2/watch/mustachetemplates closed. rewatchOnTimeout: true, errors: 0

and then the next log
[1674109129129]  GET /apis/deploy.razee.io/v1alpha2/watch/mustachetemplates errored

Note that the timestamps are very close to each other. After this point, we see 2 watches started on the kube-apiserver and the load on the kube-apiserver spikes.

Once this happens, from then on we see 2 watches close and get reopened every 5 mins
Jan 19 06:23:49 GET /apis/deploy.razee.io/v1alpha2/watch/mustachetemplates closed. rewatchOnTimeout: true, errors: 0
Jan 19 06:23:55 GET /apis/deploy.razee.io/v1alpha2/watch/mustachetemplates closed. rewatchOnTimeout: true, errors: 0
Jan 19 06:28:50 GET /apis/deploy.razee.io/v1alpha2/watch/mustachetemplates closed. rewatchOnTimeout: true, errors: 0
Jan 19 06:29:00 GET /apis/deploy.razee.io/v1alpha2/watch/mustachetemplates closed. rewatchOnTimeout: true, errors: 0

**Comment by kdai7** [comment]
Having 2 watches is normal behavior. One is for Mustache Template and the other is for Referenced Resource Manager. This new release allows you to optionally disable the Referenced Resource Manager watch. [](https://github.com/razee-io/MustacheTemplate/releases/tag/3.2.4) Since we can't see the previous logs, I am not sure if thats the behavior you were seeing before the error. The logging has also been updated to help better determine where the error is coming from.

**Comment by rgowrishankar** [comment]
This was seen with 3.1.4 where there is no referenced resource managerOn Jan 26, 2023, at 5:05 PM, kdai7 ***@***.***> wrote:﻿
Having 2 watches is normal behavior. One is for Mustache Template and the other is for Referenced Resource Manager. This new release allows you to optionally disable the Referenced Resource Manager watch.  Since we can't see the previous logs, I am not sure if thats the behavior you were seeing before the error. The logging has also been updated to help better determine where the error is coming from.

**Comment by kdai7** [comment]
should be fixed now in new release https://github.com/razee-io/MustacheTemplate/releases/tag/3.2.5
