### ISSUE TITLE
Increased load on kube-apiserver on upgrading from 3.1.4 to anything after that -- seeing additional gets on top of 5 min watches

### ISSUE THREAD

**Issue by rgowrishankar** [razee-io/MustacheTemplate#463]
**Describe the bug**
We upgraded from 3.1.4 to 3.2.3 and we are seeing additional GETs from MTP controller to kube-apiserver that seem to match up in timescale with when LD pushes an "update". The update has the same data as the previous update, we don't know why LD is pushing the update, however the FeatureFlagUpdateReceived gets updated.
https://github.com/razee-io/FeatureFlagSetLD/blob/c84cbfee3332b6181d69dfbce7af695209b500db/src/FeatureFlagSetLDController.js#L210
The FeatureFlagUpdateReceived field is one of the fields used to calculate the datahash.

**To Reproduce**
Update from 3.1.4 to 3.2.3 or really any build after 3.1.4

**Expected behavior**
Large number of calls to kube-apiserver compared to before

**Screenshots**

**Kubernetes Version (kubectl version):**
 - Client: 
 - Server:

**Additional context**

**Comment by carrolp** [comment]
Problem addressed by introduction of caching to MTP processing.  Requests to kube api should be reduced by a couple orders of magnitude starting in Release 3.2.6.
